schedules:
- cron: "*/1 * * * *"
  displayName: scheduler
  branches:
    include: [yamlnew]
    exclude: [ features/*  ] # which branches the schedule applies to
  always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

resources:
  repositories:
  - repository: new1
    type: github
    endpoint: github.com_MadhuU02
    name: MadhuU02/new1
  - repository: Template
    type: github
    endpoint: github.com_MadhuU02
    name: MadhuU02/Template

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: Template
- checkout: new1

- script: dir $(Build.SourcesDirectory)