schedules:
- cron: "*/1 * * * *"
  displayName: scheduler
  branches:
    exclude: [ features/*  ] # which branches the schedule applies to
  always: false # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

resources:
  repositories:
  - repository: new
    type: github
    endpoint: github.com_MadhuU02
    name: MadhuU02/new
  - repository: armTemplate
    type: github
    endpoint: github.com_MadhuU02
    name: MadhuU02/armTemplate

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: armTemplate
- checkout: new

- script: dir $(Build.SourcesDirectory)