# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
parameters:
- name: image
  displayName: Pool Image
  default: vs2017-win2016
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
- name: azureLocation
  displayName: azure location
  default: uksouth
  values:
  - eastus
  - japanwest
  - southindia
  - uksouth
- name: connection
  displayName: azure connection name
  type: string
  default: serviceconnection
  values:
  - serviceconnection
  - serviceconnection1
- name: resourceGroup
  displayName: resource group name
- name: storageAccountName
  displayName: storage account name
- name: storageaccountSku
  displayName: sku type
  default: Standard_LRS
  values:
  - Standard_LRS
  - Standard_GRS
  - Standard_RAGRS
  - Standard_ZRS
  - Premium_LRS
- name: storageaccountKind
  displayName: storage account kind
  default: StorageV2
  values:
  - StorageV2
  - Storage
  - BlobStorage
- name: accessTier
  displayName: access tier
  default: Hot
  values:
  - Hot
  - Cool
- name: minimumTlsVersion
  displayName: minimumTlsVersion
  default: TLS1_0
  values:
  - TLS1_0
  - TLS1_1

trigger: none
 
jobs:
- job: components
  pool:
    vmImage: ${{ parameters.image }}
 
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'ARM Template deployment: Resource Group scope'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: '${{ parameters.connection }}'
      subscriptionId: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroup)'
      location: '${{ parameters.azureLocation }}'
      templateLocation: 'Linked artifact'
      csmFile: 'storage/sta_new.json'
      overrideParameters: '-storageAccountName $(storageAccountName) -location ${{ parameters.azureLocation }} -accountType ${{ parameters.storageaccountSku }} -kind ${{ parameters.storageaccountKind }} -accessTier ${{ parameters.accessTier }} -minimumTlsVersion ${{ parameters.minimumTlsVersion }}'
      deploymentMode: 'Incremental'